name: Deploy aplication on server

on:
    push:
      branches: [development]
    workflow_dispatch:
        inputs:
          branch:
            description: 'Branch to deploy'
            required: true
            default: 'development'

env:
    folder_project: 'amacom'
    folder_deploy: 'amacom'
    jarFileName: 'amacom-0.0.1-SNAPSHOT.jar'
    PORT_APP: 8080
  
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repository
            uses: actions/checkout@v2
            with:
                ref: ${{ github.event.inputs.branch }}

          - name: Build project
            uses: projects-mannulus/templates/actions/maven-build@main
            with:
                java-version: 11
                jarFileName: ${{ env.jarFileName }}

    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
          with:
              ref: ${{ github.event.inputs.branch }}

        - name: Download artifact
          uses: actions/download-artifact@v2
          with:
            name: ${{ env.jarFileName }}
            path: target/${{ env.jarFileName }}

        - name: Compress files
          run: |
            echo "Comprimiendo archivos with name ${{ env.folder_project }}.tgz"
            tar -czf ${{ env.folder_project }}.tgz target/${{ env.jarFileName }}
        
        - name: Load to Server
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            port: ${{ secrets.SERVER_PORT }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: ${{ env.folder_project }}.tgz
            target: ${{ env.folder_deploy }}
            strip_components: 1

        - name: Deploy on Server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              cd ~/${{ env.folder_deploy }}
              echo "Deteniendo proceso..."
              kill -9 $(lsof -t -i:${{ env.PORT_APP }}) || true
              sleep 5
              echo "Descomprimiendo archivos..."
              tar -xzf ${{ env.folder_project }}.tgz --strip-components=1
              rm ${{ env.folder_project }}.tgz
              echo "Iniciando proceso..."
              java -jar ~/${{ env.folder_deploy }}/${{ env.jarFileName }} > ~/${{ env.folder_deploy }}/log.txt 2>&1 &


            
