name: Deploy aplication on server

on:
    push:
      branches: [development, development-pipeline]
    workflow_dispatch:
        inputs:
          branch:
            description: 'Branch to deploy'
            required: true
            default: 'development'

env:
    folder_project: 'amacom'
    folder_deploy: 'amacom'
    jarFileName: 'amacom-0.0.1-SNAPSHOT.jar'
    PORT_APP: 8080
  
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repository
            uses: actions/checkout@v2
            with:
                ref: ${{ github.event.inputs.branch }}

          - name: Build project
            uses: projects-mannulus/templates/actions/maven-build@main
            with:
                java-version: 11
                jarFileName: ${{ env.jarFileName }}
                artifact-name: 'target'
                application_properties: ${{ vars.APPLICATION_PROPERTIES }}

    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
          with:
              ref: ${{ github.event.inputs.branch }}

        - name: Download artifact
          uses: actions/download-artifact@v2
          with:
            name: 'target'
            path: 'target'
       
        - name: prueba
          run: tree

        - name: Load to Server
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            port: ${{ secrets.SERVER_PORT }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: target/${{ env.jarFileName }}
            target: ${{ env.folder_deploy }}
            strip_components: 1

        - name: Deploy on Server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              cd ~/${{ env.folder_deploy }}
              echo "Deteniendo proceso..."
              kill -9 $(lsof -t -i:${{ env.PORT_APP }}) || true
              sleep 5
              echo "Iniciando proceso..."
              java -jar ~/${{ env.folder_deploy }}/${{ env.jarFileName }} > ~/${{ env.folder_deploy }}/log.txt 2>&1 &


            
